### ISSUE TITLE
Copyright comment style

### ISSUE THREAD

**Issue by isuda** [lee-dohm/auto-copyright#15]
I was using this plugin for a single line copyright. It inserted the copyright headers like this:

// Copyright ... 

Which was great. Now though, it inserts the copyright like this:

/*Copyright ... */

Which does not fit our code style guidelines.

Is it possible to change the format of the comments that auto-copyright uses?

**Comment by lee-dohm** [comment]
Not specifically. auto-copyright uses an Atom API function to comment the selection. The Atom API chooses the format based on the language definition. When I get a chance, I'll see if there is something I can do to make it so you can choose between line or block comments on languages that support it.

**Comment by nikmartin** [comment]
So, as a follow up to this, do I have any control over the style of comments that get used in my project? I know this is probably an atom question, but I just installed this package and was surprised that just the opposite happened to me: I defined a multiline copyright and it was inserted like:
```
//
// Copyright © 2013, 2014, 2015 by Open Frame LLC 
// All Rights reserved.
// See full terms and conditions in LICENSE.txt
//
```
When I use `/* */ ` style block comments as a standard copyright header

**Comment by isuda** [comment]
@nikmartin - I found that this was a problem with the typescript language grammar I was using at the time. The grammar has since been fixed... I do not know to make atom use those kind of comments unfortunately.
