### ISSUE TITLE
Buffer can not be 0

### ISSUE THREAD

**Issue by raphaelcohn** [lee-dohm/auto-copyright#18]
Please allow setting buffer to 0 in the settings pane. As a work around, buffer can be set to 0 by editing the cson.

**Comment by BLOODTIDE12** [comment]
:+1:

**Comment by BLOODTIDE12** [comment]
Yeah I was surprised to see that option wasn't available through the UI

**Comment by lee-dohm** [comment]
Buffer has been able to be [set to zero for a number of years now.](https://github.com/lee-dohm/auto-copyright/blob/0e7bf734bfd4bb7dbe358dd29d1b6b1ca83b17b0/lib/main.coffee#L13)
